const mongoose = require("mongoose");
const { Schema } = mongoose;

// Define the schema for Fantasy Points
const fantasyPointsSchema = new Schema(
  {
    T20: {
      playing11: Number,
      wicket: Number,
      run: Number,
      catch: Number,
      boundary: Number,
      consecutiveBoundary: Number,
      six: Number,
      consecutiveSix: Number,
      twentyRunBonus: Number,
      thityRunBonus: Number,
      halfCenturyBonus: Number,
      centuryBonus: Number,
      doubleCenturyBonus: Number,
      dismissalForADuck: Number,
      dismissalForAGoldenDuck: Number,
      twoWicketBonus: Number,
      threWicketBonus: Number,
      fourWicketBonus: Number,
      fiveWicketBonus: Number,
      sixWicketBonus: Number,
      maidenOver: Number,
      stumping: Number,
      runOutDirectHit: Number,
      runOutNotDirectHit: Number,
    },
    T10: {
      playing11: Number,
      wicket: Number,
      run: Number,
      catch: Number,
      boundary: Number,
      consecutiveBoundary: Number,
      six: Number,
      consecutiveSix: Number,
      twentyRunBonus: Number,
      thirtyRunBonus: Number,
      halfCenturyBonus: Number,
      centuryBonus: Number,
      doubleCenturyBonus: Number,
      dismissalForADuck: Number,
      dismissalForAGoldenDuck: Number,
      twoWicketBonus: Number,
      threeWicketBonus: Number,
      fourWicketBonus: Number,
      fiveWicketBonus: Number,
      sixWicketBonus: Number,
      maidenOver: Number,
      stumping: Number,
      runOutDirectHit: Number,
      runOutNotDirectHit: Number,
    },
    ODI: {
      playing11: Number,
      wicket: Number,
      run: Number,
      catch: Number,
      boundary: Number,
      consecutiveBoundary: Number,
      six: Number,
      consecutiveSix: Number,
      fiftyRunBonus: Number,
      seventyRunBonus: Number,
      halfCenturyBonus: Number,
      centuryBonus: Number,
      doubleCenturyBonus: Number,
      dismissalForADuck: Number,
      dismissalForAGoldenDuck: Number,
      twoWicketBonus: Number,
      threeWicketBonus: Number,
      fourWicketBonus: Number,
      fiveWicketBonus: Number,
      sixWicketBonus: Number,
      maidenOver: Number,
      stumping: Number,
      runOutDirectHit: Number,
      runOutNotDirectHit: Number,
    },
    TEST: {
      playing11: Number,
      wicket: Number,
      run: Number,
      catch: Number,
      boundary: Number,
      consecutiveBoundary: Number,
      six: Number,
      consecutiveSix: Number,
      fiftyRunBonus: Number,
      hundredRunBonus: Number,
      halfCenturyBonus: Number,
      centuryBonus: Number,
      doubleCenturyBonus: Number,
      tripleCenturyBonus: Number,
      dismissalForADuck: Number,
      dismissalForAGoldenDuck: Number,
      twoWicketBonus: Number,
      threeWicketBonus: Number,
      fourWicketBonus: Number,
      fiveWicketBonus: Number,
      sixWicketBonus: Number,
      maidenOver: Number,
      stumping: Number,
      runOutDirectHit: Number,
      runOutNotDirectHit: Number,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

// Create the model
const FantasyPoint = mongoose.model("FantasyPoint", fantasyPointsSchema);

module.exports = FantasyPoint;
